test: Add tests for server and config
abbeyhrt/keep-up-graphql pull request #4
Opened 2018-03-30 17:56 UTC by abbeyhrt

Added tests for just the server and the config. 

#### Changelog

**New**

config_test.go
server_test.go

2018-03-30 18:01 UTC, joshblack requested changes
Want to add in a check for the DB config as well in `config_test`?

2018-04-03 17:25 UTC, joshblack commented on .env.template
> -export DB_NAME=keep_up_dev
Did you mean to remove these?

2018-04-03 17:26 UTC, joshblack commented on internal/config/config_test.go
> +
Extra newline

2018-04-03 17:26 UTC, joshblack approved these changes

2018-04-03 17:26 UTC, joshblack commented
Just some formatting notes and one about `env.template` and then should be good to go 👍

2018-04-03 17:46 UTC, abbeyhrt commented on .env.template
> -export DB_NAME=keep_up_dev
for some reason, i thought you had said that the .env.template file needed to be changed to .env?

2018-04-03 19:42 UTC, merged